# Execute repository tests.
name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        houdini-version: ["20.5"]

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup licensing
        uses: captainhammy/setup-hserver-action@v1
        with:
          server: ${{ secrets.LICENSE_SERVER }}
          client_id: ${{ secrets.SESI_CLIENT_ID }}
          client_secret_key: ${{ secrets.SESI_SECRET_KEY }}

      - name: Install dependencies
        run: python3 -m pip install tox tox-gh-actions coverage

      - name: Test with tox
        run: tox

      # Install rez dependencies
      - name: Install Rez Packages
        uses: captainhammy/install-rez-packages-action@v1
        with:
          files: requirements.txt

      - name: Clone you-can-call-me-houdini
        run: |
          mkdir -p ${{ runner.temp }}
          git -C ${{ runner.temp }} clone https://github.com/captainhammy/you-can-call-me-houdini.git
          cd  ${{ runner.temp }}/you-can-call-me-houdini
          rez build --install

      # Build rez packages
      - name: Build Package
        uses: captainhammy/build-rez-package-action@v1

      # Test rez package
      - name: Test Package
        uses: captainhammy/test-rez-package-action@v1

#      - name: Workaround for codecov/feedback#263
#        run: |
#          git config --global --add safe.directory "$GITHUB_WORKSPACE"
#
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v5
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          slug: captainhammy/houdini-recent-files-menu
