# Execute repository tests.
name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        houdini-version: ["20.5", "21.0"]

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Mark workspace as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up licensing
        uses: captainhammy/setup-hserver-action@v1
        with:
          server: ${{ secrets.LICENSE_SERVER }}
          client_id: ${{ secrets.SESI_CLIENT_ID }}
          client_secret_key: ${{ secrets.SESI_SECRET_KEY }}

      - name: Install dependencies
        run: python3 -m pip install tox tox-gh-actions coverage

      # Perform static analysis tests, as well as testing building documentation.
      - name: Test with tox
        run: tox

      # Install rez dependencies
      - name: Install Rez Packages
        uses: captainhammy/install-rez-packages-action@v1
        with:
          files: requirements.txt,test_requirements.txt

      # Build non-Python dependencies
      - name: Build houdini-core-tools
        uses: captainhammy/build-rez-package-action@v1
        with:
          from_git: https://github.com/captainhammy/you-can-call-me-houdini.git

      # Build rez packages
      - name: Build Current Rez Package
        uses: captainhammy/build-rez-package-action@v1

      # Test rez package
      - name: Test Current Rez Package
        uses: captainhammy/test-rez-package-action@v1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: captainhammy/houdini-recent-files-menu
